#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

APP=build/MeetingFlyby.app
GEN=Sources/MeetingFlyby/BundledCredentials.swift

# Generate the credentials file from local, gitignored values. Never committed — this is
# why a repo-visibility mistake can't leak the OAuth client.
CLIENT_ID=""
CLIENT_SECRET=""
if [ -f credentials.env ]; then
  # shellcheck disable=SC1091
  set -a; . ./credentials.env; set +a
  CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
  CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
fi

if [ -z "$CLIENT_ID" ]; then
  echo "note: credentials.env has no GOOGLE_CLIENT_ID — building without bundled Google sign-in."
  echo "      (users can still paste their own Client ID, or use the macOS Calendar option)"
fi

cat > "$GEN" <<SWIFT
// GENERATED BY build.sh — DO NOT EDIT, DO NOT COMMIT (gitignored).
// Values come from credentials.env so the OAuth client never enters git history.
import Foundation

enum BundledCredentials {
    static let googleClientID: String? = ${CLIENT_ID:+"\"$CLIENT_ID\""}${CLIENT_ID:-nil}
    static let googleClientSecret: String? = ${CLIENT_SECRET:+"\"$CLIENT_SECRET\""}${CLIENT_SECRET:-nil}
}
SWIFT

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

swiftc -O -o "$APP/Contents/MacOS/MeetingFlyby" \
  Sources/MeetingFlyby/*.swift \
  -framework Cocoa -framework EventKit -framework AVFoundation -framework Network -framework CryptoKit

cp Info.plist "$APP/Contents/Info.plist"
cp Sounds/*.wav "$APP/Contents/Resources/"
codesign --force --options runtime -s - "$APP" 2>/dev/null || codesign --force -s - "$APP"

echo "Built $APP"
