#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

APP=build/MeetingFlyby.app
GEN=Sources/MeetingFlyby/BundledCredentials.swift

# Deployment target. Set explicitly: without -target, swiftc stamps the BUILD MACHINE's OS
# version as the minimum, so the app silently refuses to launch on any older macOS.
# 11.0 (Big Sur) is the real floor — SF Symbols are used throughout the UI.
DEPLOY_TARGET=11.0

# --- Credentials -------------------------------------------------------------------------
# Generated from a local, gitignored credentials.env so the OAuth client never enters git
# history — a repo visibility mistake then can't leak it.
CLIENT_ID=""
CLIENT_SECRET=""
if [ -f credentials.env ]; then
  # shellcheck disable=SC1091
  set -a; . ./credentials.env; set +a
  CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
  CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
fi

if [ -z "$CLIENT_ID" ]; then
  echo "note: no GOOGLE_CLIENT_ID in credentials.env — building without bundled Google sign-in."
  echo "      (users can still paste their own Client ID, or use the macOS Calendar option)"
fi

if [ -n "$CLIENT_ID" ]; then ID_LIT="\"$CLIENT_ID\""; else ID_LIT="nil"; fi
if [ -n "$CLIENT_SECRET" ]; then SECRET_LIT="\"$CLIENT_SECRET\""; else SECRET_LIT="nil"; fi

cat > "$GEN" <<SWIFT
// GENERATED BY build.sh — DO NOT EDIT, DO NOT COMMIT (gitignored).
// Values come from credentials.env so the OAuth client never enters git history.
import Foundation

enum BundledCredentials {
    static let googleClientID: String? = $ID_LIT
    static let googleClientSecret: String? = $SECRET_LIT
}
SWIFT

# --- Compile ----------------------------------------------------------------------------
rm -rf "$APP" build/obj
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" build/obj

FRAMEWORKS=(-framework Cocoa -framework EventKit -framework AVFoundation -framework Network -framework CryptoKit)

# Universal: a single-arch build won't run on Intel Macs at all.
for ARCH in arm64 x86_64; do
  echo "  compiling $ARCH (min macOS $DEPLOY_TARGET)…"
  swiftc -O -target "${ARCH}-apple-macos${DEPLOY_TARGET}" \
    -o "build/obj/MeetingFlyby-${ARCH}" \
    Sources/MeetingFlyby/*.swift "${FRAMEWORKS[@]}"
done

lipo -create -output "$APP/Contents/MacOS/MeetingFlyby" \
  build/obj/MeetingFlyby-arm64 build/obj/MeetingFlyby-x86_64
rm -rf build/obj

cp Info.plist "$APP/Contents/Info.plist"
cp Sounds/*.wav "$APP/Contents/Resources/"
cp Icon/AppIcon.icns "$APP/Contents/Resources/"
codesign --force --options runtime -s - "$APP" 2>/dev/null || codesign --force -s - "$APP"

echo "Built $APP"
lipo -archs "$APP/Contents/MacOS/MeetingFlyby" | sed 's/^/  architectures: /'
